# Generated by Django 3.2.9 on 2022-01-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField(max_length=100)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Goa', 'Goa')], max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_location', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='Profilepics/')),
                ('my_file', models.FileField(upload_to='resume_doc/')),
            ],
        ),
    ]
